omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]
OUT_DIR = "gen"

[[buildscript]]
[buildscript.gen_srcs]
env = { OUT_DIR = ".." }
files = ["host.rs"]
mapped = { "host.rs" = "gen/host.rs" }

[extra_mapped_srcs]

[platform_fixup]
