cfgs = ["asm", "switchable_stack"]

# Only build psm_s for the os & arch targets below.
buildscript = []

# overlay/src/lib.rs is a tweaked copy of vendor/psm-0.1.17/src/lib.rs
# Be sure to update and re-tweak if necessary if upgrading.
# Look for lines marked FIXUP.
overlay = "overlay"

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.buildscript.cxx_library]
name = "psm_s-linux-x86_64"
srcs = ["src/arch/x86_64.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "macos"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "macos"))'.buildscript.cxx_library]
name = "psm_s-macos"
srcs = ["src/arch/x86_64.s"]
compiler_flags = ["-xassembler-with-cpp"]
preprocessor_flags = ["-DCFG_TARGET_OS_macos"]
headers = ["src/arch/psm.h"]

[[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.buildscript.cxx_library]
name = "psm_s-linux-aarch64"
srcs = ["src/arch/aarch_aapcs64.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]
