# overlay = "overlay"
cfgs = [
    'feature="c"',
    'feature="cc"',
    'feature="compiler-builtins"',
    'feature="core"',
    'feature="default"',
    'feature="rustc-dep-of-std"',
    'bootstrap',
    'feature="unstable"',
    'feature="mem-unaligned"',
    '__absvdi2="optimized-c"',
    '__absvsi2="optimized-c"',
    '__absvti2="optimized-c"',
    '__addvdi3="optimized-c"',
    '__addvsi3="optimized-c"',
    '__addvti3="optimized-c"',
    '__clzdi2="optimized-c"',
    '__clzsi2="optimized-c"',
    '__clzti2="optimized-c"',
    '__cmpdi2="optimized-c"',
    '__cmpti2="optimized-c"',
    '__ctzdi2="optimized-c"',
    '__ctzsi2="optimized-c"',
    '__ctzti2="optimized-c"',
    '__divdc3="optimized-c"',
    '__divsc3="optimized-c"',
    '__divxc3="optimized-c"',
    '__extendhfsf2="optimized-c"',
    '__ffsti2="optimized-c"',
    '__floatdixf="optimized-c"',
    '__floatundixf="optimized-c"',
    '__int_util="optimized-c"',
    '__muldc3="optimized-c"',
    '__mulsc3="optimized-c"',
    '__mulvdi3="optimized-c"',
    '__mulvsi3="optimized-c"',
    '__mulvti3="optimized-c"',
    '__mulxc3="optimized-c"',
    '__negdf2="optimized-c"',
    '__negdi2="optimized-c"',
    '__negsf2="optimized-c"',
    '__negti2="optimized-c"',
    '__negvdi2="optimized-c"',
    '__negvsi2="optimized-c"',
    '__negvti2="optimized-c"',
    '__paritydi2="optimized-c"',
    '__paritysi2="optimized-c"',
    '__parityti2="optimized-c"',
    '__popcountdi2="optimized-c"',
    '__popcountsi2="optimized-c"',
    '__popcountti2="optimized-c"',
    '__powixf2="optimized-c"',
    '__subvdi3="optimized-c"',
    '__subvsi3="optimized-c"',
    '__subvti3="optimized-c"',
    '__truncdfhf2="optimized-c"',
    '__truncsfhf2="optimized-c"',
    '__ucmpdi2="optimized-c"',
    '__ucmpti2="optimized-c"'
]
[[buildscript]]
[buildscript.rustc_flags]
